INSERT INTO Category
VALUES
(1, 'F', 'spring', 'adult'),
(2, 'F', 'winter', 'adult'),
(3, 'M', 'autumn', 'adult'),
(4, 'M', 'summer', 'adult'),
(5, 'M', 'summer', 'kids'),
(6, 'F', 'spring', 'kids'),
(7, 'F', 'autumn', 'adult'),
(8, 'F', 'winter', 'adult'),
(9, 'M', 'spring', 'adult'),
(10, 'M', 'summer', 'adult'),
(11, 'M', 'autumn', 'kids'),
(12, 'F', 'summer', 'kids'),
(13, 'M', 'spring', 'adult'),
(14, 'F', 'winter', 'adult'),
(15, 'M', 'summer', 'adult'),
(16, NULL, 'autumn', 'kids'),
(17, 'M', 'winter', 'adult'),
(18, 'F', 'summer', 'adult'),
(19, 'M', 'winter', 'kids'),
(20, 'F', 'spring', 'kids'),
(21, 'M', NULL, 'adult'),
(22, 'F', NULL, 'adult'),
(23, NULL, NULL, 'kids'),
(24, NULL, 'summer', NULL);
